schema: 7.0.0 # Earliest compatible MO2-LINT Version

resources:

  # <resource>:
  #   version: "<version>"
  #   download_url: "<download-url>"
  #   #OPTIONAL checksum: "<sha256-checksum-of-archive>"
  #   #OPTIONAL checksum_internal: "<sha256-checksum-of-important-file-inside-archive>" # file being checked inside the archive

  mod_organizer:
    version: "2.5.2"
    download_url: "https://github.com/ModOrganizer2/modorganizer/releases/download/v2.5.2/Mod.Organizer-2.5.2.7z"
    checksum: "e6376efd87fd5ddd95aee959405e8f067afa526ea6c2c0c5aa03c5108bf4a815"
    path_internal: "ModOrganizer.exe"
    checksum_internal: "442b354a8f34754da0048654c44d27f51628feba54ce46c3187cf58d6c43e622" # ModOrganizer.exe

  java:
    version: "8u312-b07"
    download_url: "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip"
    checksum: "a4623365d70e7bc969e84b7f29b6b2eecb6c0686863ed67651506e2b5adf43b0"
    path_internal: "jdk8u312-b07-jre/bin/java.exe"
    checksum_internal: "4bdb429326d8ac8308a9ad2fbd4edcb19dff67e153ca81673a57cf1cd575081e" # jdk8u312-b07-jre/bin/java.exe
    file_whitelist:
      subdirectory: jdk8u312-b07-jre

  winetricks:
    version: "latest-autobuild"
    download_url: "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"

  # Fallback for hosts without cabextract (e.g. SteamOS)
  cabextract:
    version: "1.9-3"
    download_url: "https://deb.debian.org/debian/pool/main/c/cabextract/cabextract_1.9-3_amd64.deb"
    fallback_url: "https://snapshot.debian.org/archive/debian/20230611T000000Z/pool/main/c/cabextract/cabextract_1.9-3_amd64.deb"
    checksum: "0b02139c1bc170c6ee107fd480da5d290bdeba7cbbb881d95d9ff6544ccda748"
    path_internal: "./usr/bin/cabextract"

  libmspack:
    version: "0.11-1"
    download_url: "https://deb.debian.org/debian/pool/main/libm/libmspack/libmspack0_0.11-1_amd64.deb"
    fallback_url: "https://snapshot.debian.org/archive/debian/20230611T000000Z/pool/main/libm/libmspack/libmspack0_0.11-1_amd64.deb"
    checksum: "6695d3b9cc51a874feec328b40df0a59a2849c3fcc8cff77aa5f8d9f8e43fdca"
    path_internal: "./usr/lib/x86_64-linux-gnu/libmspack.so.0.1.0"

  vcredist_x86:
    version: "14.44.35211"
    download_url: "https://download.visualstudio.microsoft.com/download/pr/7ebf5fdb-36dc-4145-b0a0-90d3d5990a61/0C09F2611660441084CE0DF425C51C11E147E6447963C3690F97E0B25C55ED64/VC_redist.x86.exe"
    checksum: "0c09f2611660441084ce0df425c51c11e147e6447963c3690f97e0b25c55ed64"

  vcredist_x64:
    version: "14.44.35211"
    download_url: "https://download.visualstudio.microsoft.com/download/pr/7ebf5fdb-36dc-4145-b0a0-90d3d5990a61/CC0FF0EB1DC3F5188AE6300FAEF32BF5BEEBA4BDD6E8E445A9184072096B713B/VC_redist.x64.exe"
    checksum: "cc0ff0eb1dc3f5188ae6300faef32bf5beeba4bdd6e8e445a9184072096b713b"
